lsc mag
PaddlePaddle/PGL pull request #235
Opened 2021-04-15 04:20 UTC by sys1874

2021-04-15 04:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PGL?pullRequest=235) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PGL?pullRequest=235) before we can accept your contribution.<br/><hr/>**shiyunsheng01** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PGL?pullRequest=235) it.</sub>

2021-04-15 04:25 UTC, Yelrose commented on ogb_examples/lsc/MAG240M/dataset/base_dataset.py
> +#     np.random.shuffle(buffer)
problem

2021-04-15 04:25 UTC, Yelrose requested changes

2021-04-15 04:25 UTC, Yelrose commented on ogb_examples/lsc/MAG240M/dataset/data_generator.py
> +        np.random.shuffle(self.train_idx)
Not Shuffle Here, seed is not the same

2021-04-16 02:45 UTC, sys1874 commented on ogb_examples/lsc/MAG240M/dataset/base_dataset.py
> +#     np.random.shuffle(buffer)
fix

2021-04-16 02:45 UTC, sys1874 commented on ogb_examples/lsc/MAG240M/dataset/data_generator.py
> +        np.random.shuffle(self.train_idx)
fix

2021-05-06 02:40 UTC, Yelrose approved these changes
LGTM

2021-05-06 02:40 UTC, merged