add appnp for small dataset
PaddlePaddle/PGL pull request #286
Opened 2021-07-12 03:26 UTC by DesmonDay

2021-07-12 03:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PGL?pullRequest=286) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PGL?pullRequest=286) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: DesmonDay<br/>:x: daisiming<br/><hr/>**daisiming** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PGL?pullRequest=286) it.</sub>

2021-07-13 06:27 UTC, Yelrose commented on examples/kddcup2021/WikiKG90M/post_smoothing/appnp.py
> +    feat_path = os.path.join('/home/work/suweiyue/Shared/WikiKG90M/RPS/KGEmbedding-OTE/models', '%s_%s' % (model, dataset))
The name of the directory should be anonymous.

2021-07-13 07:35 UTC, Yelrose requested changes

2021-07-13 07:35 UTC, Yelrose commented on examples/kddcup2021/WikiKG90M/post_smoothing/appnp.py
> +        h_index = np.where(edges[:, 0] == eid)
复杂度略高

2021-07-13 07:35 UTC, Yelrose commented on examples/kddcup2021/WikiKG90M/post_smoothing/appnp.py
> +        h_index = np.where(edges[:, 0] == eid)
O(N * E)

2021-08-04 02:37 UTC, Liwb5 commented on examples/kddcup2021/WikiKG90M/post_smoothing/appnp.py
> +    # 格式 实体的邻居：[[a, b, c], [r1, r2, r3], [1, -1, 1]](包括方向)，多个实体就用列表存起来
尽量不要用中文注释. 特别是文件开头没有加上: #-*- coding: utf-8 -*-

2021-11-24 07:15 UTC, closed without merging