Add example code for REP
PaddlePaddle/PGL pull request #408
Opened 2022-04-28 13:29 UTC by DesmonDay

Provide official code for paper **Simple and Effective Relation-based Embedding Propagation for Knowledge Representation Learning**.

2022-04-28 13:32 UTC, Yelrose commented on examples/REP/ote_orth.py
> +class Orth_OTE():
OrthOTE

2022-04-28 14:03 UTC, kirayummy requested changes
place the REP to /apps/Graph4KG/

2022-05-06 09:23 UTC, Yelrose approved these changes
LGTM

2022-05-07 02:57 UTC, DesmonDay commented on apps/Graph4KG/examples/REP/README.md
> +In our paper, for FB15k-237 and WN18RR datasets, we use [KGEmbedding-OTE](https://github.com/JD-AI-Research-Silicon-Valley/KGEmbedding-OTE) to train KG embeddings, including 5 models we use in paper.
done

2022-05-07 03:25 UTC, kirayummy approved these changes

2022-05-09 14:45 UTC, merged