update utils.transform
PaddlePaddle/PGL pull request #431
Opened 2022-07-11 04:24 UTC by dongZheX

Add two functions "to_dense_batch" and "filter_adj" to pgl.utils.transform

2022-07-11 04:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PGL?pullRequest=431) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PGL?pullRequest=431) before we can accept your contribution.<br/><hr/>**dongzhex** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PGL?pullRequest=431) it.</sub>

2022-07-12 03:15 UTC, Yelrose commented on pgl/nn/gmt.py
> +    def forward(self, Q, K, graph=None, mask=None):
需要补一下 forward的接口说明

2022-07-12 03:23 UTC, Yelrose requested changes

2022-07-12 03:23 UTC, Yelrose commented on pgl/nn/gmt.py
> +    def forward(self, x, graph, mask):
补接口说明

2022-07-12 03:23 UTC, Yelrose commented on pgl/nn/gmt.py
> +    def forward(self, x, graph, mask):
补接口说明

2022-07-12 03:23 UTC, Yelrose commented on pgl/nn/gmt.py
> +        Conv=None,
参数名Conv不建议大写

2022-07-12 03:23 UTC, Yelrose commented on pgl/nn/pool.py
> +    def forward(self, graph, x):
补接口说明

2022-07-12 03:23 UTC, Yelrose commented on pgl/nn/sag_pool.py
> +    def __init__(self, input_dim, ratio=0.5, GNN=GCNConv, min_score=None,
默认参数不建议是GNN=GCNConv， 最好是GNN=None，然后在函数内，设定Default值为GCNConv

2022-07-12 05:54 UTC, DesmonDay commented
需要安装 pre-commit来提交修改

2022-07-12 05:56 UTC, DesmonDay commented on pgl/nn/gmt.py
> +import paddle
文件开头参考其他文件，加一下 license

2022-07-12 05:59 UTC, DesmonDay commented on pgl/nn/gmt.py
> +""""""
没用的注释记得删掉

2022-08-03 07:03 UTC, Yelrose commented on pgl/nn/pool.py
> +                 GNN=None,
GNN 这个改成 小写

2022-08-03 07:36 UTC, Yelrose approved these changes
LGTM

2022-08-03 08:47 UTC, Yelrose requested changes
segment_topk 在一定情况下会报错，需修复

2022-08-04 07:53 UTC, Yelrose approved these changes
LGTM

2022-08-04 07:54 UTC, merged