fix segment ops
PaddlePaddle/PGL pull request #445
Opened 2022-08-02 09:52 UTC by DesmonDay

2022-08-02 10:04 UTC, Yelrose requested changes

2022-08-02 10:04 UTC, Yelrose commented on pgl/math.py
>      pool_type = pool_type.upper()
segment_pool 改成 if else，调用其他segment op

2022-08-02 10:57 UTC, DesmonDay commented on pgl/math.py
>      pool_type = pool_type.upper()
done

2022-08-03 05:26 UTC, Yelrose approved these changes
LGTM

2022-08-03 05:26 UTC, merged