Change 0 dim tensor usage
PaddlePaddle/PGL pull request #490
Opened 2022-11-11 10:44 UTC by DesmonDay

## Description
1. 代码中所有的``x.numpy()[0]``，框架同学建议修改为 `float(x)`，以适配0维Tensor的场景。`float(x)`的写法在`x`为1D或0D Tensor时均能正常使用。

2022-11-11 12:16 UTC, zhouwei25 approved these changes
全量已修改，经判断是shape为[1]的Tensor。后续可以关注下改动后是否模型正常运行

2022-11-14 04:01 UTC, Yelrose requested changes
请按数据类型修改

2022-11-14 04:01 UTC, Yelrose commented on examples/NeurIPS2022-OGB-Challenge/MAG240M/dataset/new_dataset_p2p.py
> +                    edge_split.append(float(paddle.sum(neighbor_counts)))
是int类型

2022-11-14 04:41 UTC, DesmonDay commented on examples/NeurIPS2022-OGB-Challenge/MAG240M/dataset/new_dataset_p2p.py
> +                    edge_split.append(float(paddle.sum(neighbor_counts)))
done

2022-11-14 05:05 UTC, Yelrose approved these changes
LGTM

2022-11-14 05:05 UTC, merged