Refine PGLBox readme
PaddlePaddle/PGL pull request #514
Opened 2022-12-13 07:23 UTC by DesmonDay

2022-12-13 13:15 UTC, Yelrose commented on apps/PGLBox/README.md
> +cat user_configs/mag240m_metapath2vec.yaml
为何这个是cat

2022-12-13 14:47 UTC, Liwb5 requested changes

2022-12-13 14:47 UTC, Liwb5 commented on apps/PGLBox/README.md
> +wget https://baidu-pgl.gz.bcebos.com/pglbox/data/MAG240M/preproceesed_mag240m.tar
https://baidu-pgl.gz.bcebos.com/pglbox/data/MAG240M/preprocessed_MAG240M.tar.gz  真正的地址

2022-12-14 08:15 UTC, Yelrose approved these changes
LGTM

2022-12-14 08:34 UTC, Liwb5 approved these changes

2022-12-14 08:36 UTC, merged