Update pglbox
PaddlePaddle/PGL pull request #537
Opened 2023-03-01 06:56 UTC by DesmonDay

2023-03-02 06:23 UTC, Yelrose requested changes

2023-03-02 06:23 UTC, Yelrose commented on apps/PGLBox/src/config_fleet.py
> +    #sparse_config['sparse_table_class'] = sparse_table_class
sparse_table_class没起作用？

2023-03-02 06:27 UTC, DesmonDay commented on apps/PGLBox/src/config_fleet.py
> +    #sparse_config['sparse_table_class'] = sparse_table_class
已改

2023-03-03 00:22 UTC, Liwb5 commented on apps/PGLBox/README.md
> +如果想要制定训练或者infer的节点目录，可以参考[这里](./wiki/train_infer_from_file_ch.md)
一个新手应该不懂这句话是什么意思。改成下面这样：

默认情况下，PGLBox会训练图数据中所有节点并且预测出所有节点的embedding。如果用户只想训练部分节点，或者只预测部分节点，PGLBox提供了相应的功能支持，详情请参考xx。

2023-03-03 00:22 UTC, Liwb5 commented on apps/PGLBox/README.md
> +如果想要制定训练或者infer的节点目录，可以参考[这里](./wiki/train_infer_from_file_ch.md)
后面也可以考虑写一个示例来展示这种功能。

2023-03-03 00:22 UTC, Liwb5 commented on apps/PGLBox/src/cluster_train_and_infer.py
> +            "DEPENDENCY_HOME")  # see env_run/scripts/train.sh for details
bash脚本并没有DEPENDENCY_HOME这个变量。

2023-03-03 03:33 UTC, DesmonDay commented on apps/PGLBox/src/cluster_train_and_infer.py
> +            "DEPENDENCY_HOME")  # see env_run/scripts/train.sh for details
嗯嗯，我当时写的时候也有注意到，不过想着目前不会有人使用这块功能，就没管了。。我后面改掉。

2023-03-07 12:12 UTC, DesmonDay commented on apps/PGLBox/src/cluster_train_and_infer.py
> +            "DEPENDENCY_HOME")  # see env_run/scripts/train.sh for details
直接去掉这块地方了，现在还没有pretrained_model

2023-03-07 12:15 UTC, Yelrose approved these changes

2023-03-07 12:16 UTC, merged