Add GaAN model
PaddlePaddle/PGL pull request #81
Opened 2020-05-20 10:32 UTC by WenjinW

- add GaAN in pgl.layers.conv
- add GaAN example in examples

2020-05-20 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PGL?pullRequest=81) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PGL?pullRequest=81) before we can accept your contribution.<br/><hr/>**wangwenjin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PGL?pullRequest=81) it.</sub>

2020-05-21 02:56 UTC, kirayummy requested changes
supply the experimental result of GaAN

2020-05-21 04:42 UTC, WenjinW commented
The experiment result of GaAN on ogbn-proteins is updated

2020-05-22 09:17 UTC, kirayummy approved these changes

2020-05-22 15:30 UTC, merged